#!/usr/bin/env bun
import { readFileSync, writeFileSync } from "node:fs";

interface Scene {
  id: number;
  title: string;
  durationSec: number;
  titleCard?: string;
  files: string[];
  show: string;
  highlight?: string;
  narration?: string;
}

interface Plan {
  title: string;
  scenes: Scene[];
}

function parsePlan(md: string): Plan {
  const titleMatch = md.match(/^# Walkthrough:\s*(.+)$/m);
  const title = titleMatch?.[1]?.trim() ?? "Walkthrough";

  const headerRe = /^## Scene (\d+)\s*[—-]\s*(.+?)\s*\((\d+(?:\.\d+)?)s\)\s*$/gm;
  const headers = [...md.matchAll(headerRe)];
  const scenes: Scene[] = [];

  for (let i = 0; i < headers.length; i++) {
    const h = headers[i];
    const start = h.index! + h[0].length;
    const end = i + 1 < headers.length ? headers[i + 1].index! : md.length;
    const body = md.slice(start, end);

    const field = (name: string): string | undefined => {
      const re = new RegExp(`^\\s*[-*]\\s*${name}:\\s*(.+)$`, "m");
      const m = body.match(re);
      if (!m) return undefined;
      let v = m[1].trim();
      if (v.startsWith("`") && v.endsWith("`")) v = v.slice(1, -1);
      if (v.startsWith('"') && v.endsWith('"')) v = v.slice(1, -1);
      return v;
    };

    const filesRaw = field("Files") ?? "";
    const files =
      filesRaw === "" || filesRaw.toLowerCase() === "none"
        ? []
        : filesRaw.split(",").map((s) => s.trim()).filter(Boolean);

    scenes.push({
      id: parseInt(h[1], 10),
      title: h[2].trim(),
      durationSec: parseFloat(h[3]),
      titleCard: field("Title card"),
      files,
      show: field("Show") ?? `echo "scene ${h[1]}: ${h[2].trim()}"`,
      highlight: field("Highlight"),
      narration: field("Narration"),
    });
  }

  return { title, scenes };
}

function emitTape(plan: Plan): string {
  const out: string[] = [];
  out.push(`# Auto-generated by scene_planner.ts — DO NOT EDIT BY HAND`);
  out.push(`# Plan: ${plan.title}`);
  out.push(``);
  out.push(`Output walkthrough.mp4`);
  out.push(`Set FontSize 18`);
  out.push(`Set Width 1280`);
  out.push(`Set Height 720`);
  out.push(`Set Theme "Catppuccin Mocha"`);
  out.push(`Set TypingSpeed 25ms`);
  out.push(`Set Padding 20`);
  out.push(`Set PlaybackSpeed 1.0`);
  out.push(`Env BAT_PAGER ""`);
  out.push(`Env BAT_STYLE "numbers,grid"`);
  out.push(`Env PAGER cat`);
  out.push(``);
  out.push(`Hide`);
  out.push(`Type "clear"`);
  out.push(`Enter`);
  out.push(`Sleep 300ms`);
  out.push(`Show`);
  out.push(``);

  for (const s of plan.scenes) {
    out.push(`# ─── Scene ${s.id}: ${s.title} (${s.durationSec}s) ───`);
    out.push(`Hide`);
    out.push(`Type "clear"`);
    out.push(`Enter`);
    out.push(`Sleep 200ms`);
    out.push(`Show`);
    const cmd = s.show.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    out.push(`Type "${cmd}"`);
    out.push(`Enter`);
    out.push(`Sleep ${s.durationSec}s`);
    out.push(``);
  }

  out.push(`Hide`);
  out.push(`Type "clear"`);
  out.push(`Enter`);
  out.push(`Sleep 300ms`);
  out.push(`Show`);
  return out.join("\n") + "\n";
}

function emitManifest(plan: Plan): string {
  return (
    JSON.stringify(
      {
        title: plan.title,
        totalDurationSec: plan.scenes.reduce((a, s) => a + s.durationSec, 0),
        scenes: plan.scenes.map((s) => ({
          id: s.id,
          title: s.title,
          durationSec: s.durationSec,
          narration: s.narration,
        })),
      },
      null,
      2,
    ) + "\n"
  );
}

const args = process.argv.slice(2);
const dryRun = args.includes("--dry-run");
const planPath = args.find((a) => !a.startsWith("--")) ?? "narrative_plan.md";

const md = readFileSync(planPath, "utf8");
const plan = parsePlan(md);

if (plan.scenes.length === 0) {
  console.error(
    `No scenes found in ${planPath}. Expected '## Scene N — name (Ns)' headers.`,
  );
  process.exit(1);
}

const tape = emitTape(plan);
const manifest = emitManifest(plan);

if (dryRun) {
  console.log(`=== walkthrough.tape (${plan.scenes.length} scenes) ===`);
  console.log(tape);
  console.log(`=== manifest.json ===`);
  console.log(manifest);
} else {
  writeFileSync("walkthrough.tape", tape);
  writeFileSync("manifest.json", manifest);
  const total = plan.scenes.reduce((a, s) => a + s.durationSec, 0);
  console.log(
    `Wrote walkthrough.tape + manifest.json (${plan.scenes.length} scenes, ~${total}s total)`,
  );
}
