#!/usr/bin/env bun
import { readFileSync, writeFileSync } from "node:fs";

interface Scene {
  id: number;
  title: string;
  titleCard?: string;
  files: string[];
  show: string;
  narration?: string;
}

interface Plan {
  title: string;
  scenes: Scene[];
}

interface Manifest {
  title: string;
  totalDurationSec: number;
  scenes: { id: number; title: string; durationSec: number }[];
}

function parsePlan(md: string): Plan {
  const titleMatch = md.match(/^# Walkthrough:\s*(.+)$/m);
  const title = titleMatch?.[1]?.trim() ?? "Walkthrough";

  // Tolerate both "## Scene N — name" and legacy "## Scene N — name (Ns)"
  const headerRe = /^## Scene (\d+)\s*[—-]\s*(.+?)(?:\s*\([^)]*\))?\s*$/gm;
  const headers = [...md.matchAll(headerRe)];
  const scenes: Scene[] = [];

  for (let i = 0; i < headers.length; i++) {
    const h = headers[i];
    const start = h.index! + h[0].length;
    const end = i + 1 < headers.length ? headers[i + 1].index! : md.length;
    const body = md.slice(start, end);

    const field = (name: string): string | undefined => {
      const re = new RegExp(`^\\s*[-*]\\s*${name}:\\s*(.+)$`, "m");
      const m = body.match(re);
      if (!m) return undefined;
      let v = m[1].trim();
      if (v.startsWith("`") && v.endsWith("`")) v = v.slice(1, -1);
      if (v.startsWith('"') && v.endsWith('"')) v = v.slice(1, -1);
      return v;
    };

    const filesRaw = field("Files") ?? "";
    const files =
      filesRaw === "" || filesRaw.toLowerCase() === "none"
        ? []
        : filesRaw.split(",").map((s) => s.trim()).filter(Boolean);

    scenes.push({
      id: parseInt(h[1], 10),
      title: h[2].trim(),
      titleCard: field("Title card"),
      files,
      show: field("Show") ?? `echo "scene ${h[1]}: ${h[2].trim()}"`,
      narration: field("Narration"),
    });
  }

  return { title, scenes };
}

// vhs renders ~17% under wall-clock at TypingSpeed 25ms. Apply an inverse
// factor when sizing Sleeps from measured audio so the recorded MP4 lands
// close to the audio length on each scene.
const VHS_TIMESCALE = 1 / 0.825; // ≈1.21
const TYPE_RENDER_OVERHEAD_SEC = 0.5;

function emitTape(
  plan: Plan,
  manifest: Manifest,
): string {
  const durationById = new Map(
    manifest.scenes.map((s) => [s.id, s.durationSec]),
  );

  const out: string[] = [];
  out.push(`# Auto-generated by scene_planner.ts (audio-first) — DO NOT EDIT`);
  out.push(`# Plan: ${plan.title}`);
  out.push(``);
  out.push(`Output walkthrough.mp4`);
  out.push(`Set FontSize 18`);
  out.push(`Set Width 1280`);
  out.push(`Set Height 720`);
  out.push(`Set Theme "Catppuccin Mocha"`);
  out.push(`Set TypingSpeed 25ms`);
  out.push(`Set Padding 20`);
  out.push(`Set PlaybackSpeed 1.0`);
  out.push(`Env BAT_PAGER ""`);
  out.push(`Env BAT_STYLE "numbers,grid"`);
  out.push(`Env PAGER cat`);
  out.push(``);
  out.push(`Hide`);
  out.push(`Type "clear"`);
  out.push(`Enter`);
  out.push(`Sleep 300ms`);
  out.push(`Show`);
  out.push(``);

  for (const s of plan.scenes) {
    const audioSec = durationById.get(s.id);
    if (audioSec === undefined) {
      throw new Error(
        `Scene ${s.id} has no manifest entry; run tts.ts first.`,
      );
    }
    // Account for vhs's timescale drift and the Type render time so the
    // scene's *visible* portion lasts as long as the audio.
    const sleepSec = Math.max(
      1.0,
      (audioSec - TYPE_RENDER_OVERHEAD_SEC) * VHS_TIMESCALE,
    );

    out.push(`# ─── Scene ${s.id}: ${s.title} (audio ${audioSec}s → sleep ${sleepSec.toFixed(2)}s) ───`);
    out.push(`Hide`);
    out.push(`Type "clear"`);
    out.push(`Enter`);
    out.push(`Sleep 200ms`);
    out.push(`Show`);
    const cmd = s.show.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    out.push(`Type "${cmd}"`);
    out.push(`Enter`);
    out.push(`Sleep ${sleepSec.toFixed(2)}s`);
    out.push(``);
  }

  out.push(`Hide`);
  out.push(`Type "clear"`);
  out.push(`Enter`);
  out.push(`Sleep 300ms`);
  out.push(`Show`);
  return out.join("\n") + "\n";
}

const args = process.argv.slice(2);
const dryRun = args.includes("--dry-run");
const positional = args.filter((a) => !a.startsWith("--"));
const planPath = positional[0] ?? "narrative_plan.md";
const manifestPath = positional[1] ?? "manifest.json";

const md = readFileSync(planPath, "utf8");
const plan = parsePlan(md);

if (plan.scenes.length === 0) {
  console.error(
    `No scenes found in ${planPath}. Expected '## Scene N — name' headers.`,
  );
  process.exit(1);
}

let manifest: Manifest;
try {
  manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
} catch (e) {
  console.error(
    `Could not read manifest at ${manifestPath}. Run tts.ts first to produce per-scene measured durations.`,
  );
  process.exit(1);
}

const tape = emitTape(plan, manifest);

if (dryRun) {
  console.log(`=== walkthrough.tape (${plan.scenes.length} scenes) ===`);
  console.log(tape);
} else {
  writeFileSync("walkthrough.tape", tape);
  const totalSleep = plan.scenes.reduce((a, s) => {
    const d = manifest.scenes.find((m) => m.id === s.id)?.durationSec ?? 0;
    return a + Math.max(1.0, (d - TYPE_RENDER_OVERHEAD_SEC) * VHS_TIMESCALE);
  }, 0);
  console.log(
    `Wrote walkthrough.tape (${plan.scenes.length} scenes, ${totalSleep.toFixed(1)}s of scripted Sleep targeting ${manifest.totalDurationSec}s of audio)`,
  );
}
